# Generated by Django 2.1.5 on 2019-01-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='cvs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='angajat', to='Recruit.CV'),
        ),
    ]
