# Generated by Django 2.1.5 on 2019-01-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0002_auto_20190112_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angajat',
            name='cvs',
        ),
        migrations.AddField(
            model_name='cv',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cvs', to='Recruit.Angajat'),
        ),
    ]
